import type { ProviderPreset } from "@kako/shared";

/** Built-in provider presets (cc-switch style). */
export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: "volcengine-doubao",
    name: "火山引擎豆包",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    protocol: "openai-compatible",
    description: "火山方舟 OpenAI 兼容接口，模型 ID 为接入点 ep-xxx",
    apiKeyEnv: "ARK_API_KEY",
    exampleModels: ["ep-xxxxxxxx"],
    featured: true,
    website: "https://www.volcengine.com/product/ark",
  },
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "OPENAI_API_KEY",
    exampleModels: ["gpt-4o", "gpt-4o-mini"],
    featured: true,
    website: "https://openai.com",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "OPENROUTER_API_KEY",
    exampleModels: ["anthropic/claude-sonnet-4", "openai/gpt-4o"],
    featured: true,
    website: "https://openrouter.ai",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    exampleModels: ["deepseek-chat", "deepseek-reasoner"],
    featured: true,
    website: "https://platform.deepseek.com",
  },
  {
    id: "moonshot",
    name: "Moonshot / Kimi",
    baseUrl: "https://api.moonshot.cn/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "MOONSHOT_API_KEY",
    exampleModels: ["moonshot-v1-8k", "kimi-latest"],
    website: "https://platform.moonshot.cn",
  },
  {
    id: "zhipu",
    name: "智谱 GLM",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    protocol: "openai-compatible",
    apiKeyEnv: "ZHIPU_API_KEY",
    exampleModels: ["glm-4-plus", "glm-4-flash"],
    website: "https://open.bigmodel.cn",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "SILICONFLOW_API_KEY",
    exampleModels: ["deepseek-ai/DeepSeek-V3"],
    website: "https://siliconflow.cn",
  },
  {
    id: "dashscope",
    name: "阿里云百炼",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "DASHSCOPE_API_KEY",
    exampleModels: ["qwen-plus", "qwen-turbo"],
    website: "https://bailian.console.aliyun.com",
  },
  {
    id: "stepfun",
    name: "阶跃星辰",
    baseUrl: "https://api.stepfun.com/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "STEPFUN_API_KEY",
    exampleModels: ["step-2-16k"],
    website: "https://platform.stepfun.com",
  },
  {
    id: "minimax",
    name: "MiniMax",
    baseUrl: "https://api.minimax.chat/v1",
    protocol: "openai-compatible",
    apiKeyEnv: "MINIMAX_API_KEY",
    exampleModels: ["abab6.5s-chat"],
    website: "https://www.minimaxi.com",
  },
  {
    id: "ollama",
    name: "Ollama（本地）",
    baseUrl: "http://localhost:11434/v1",
    protocol: "openai-compatible",
    description: "本地 Ollama OpenAI 兼容端点",
    exampleModels: ["llama3.2", "qwen2.5"],
    website: "https://ollama.com",
  },
  {
    id: "custom",
    name: "自定义",
    baseUrl: "",
    protocol: "openai-compatible",
    description: "自定义 OpenAI 兼容端点，需手动填写所有字段",
  },
];

export function getPreset(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((p) => p.id === id);
}
